version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current # Use a Node.js environment
    steps:
      - checkout
      - run: npm install
      - run: npm run build # Build your project
      - run: npm test # Run your tests

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: npm install
      - run:
          name: Deploy to Staging
          command: |
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              # Deploy your branch to a staging environment
              # This can be done using a script or a CLI tool specific to your hosting provider
              echo "Deploying ${CIRCLE_BRANCH} to staging"
              # Example: npm run deploy-staging
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: main # Ignore the main branch for deployment job
